module.exports = {
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,

    SOCKET_UPDATE: "update",
    SOCKET_NEW_PLAYER: "new-player",
    SOCKET_PLAYER_ACTION: "player-action",
    SOCKET_CHAT_CLIENT_SERVER: "chat-client-to-server",
    SOCKET_CHAT_SERVER_CLIENT: "chat-server-to-client",
    SOCKET_DISCONNECT: "disconnect",

    SOCKET_CARD_PLAYED: "card-played",

    DRAWING_BASE_WIDTH: 30,
    DRAWING_CARD_WIDTH: 25,

    DRAWING_IMG_BASE_PATH: "/client-side/img",

    DRAWING_IMG_CARDS: [
        "10C",
        "10D",
        "10H",
        "10S",
        "2C",
        "2D",
        "2H",
        "2S",
        "3C",
        "3D",
        "3H",
        "3S",
        "4C",
        "4D",
        "4H",
        "4S",
        "5C",
        "5D",
        "5H",
        "5S",
        "6C",
        "6D",
        "6H",
        "6S",
        "7C",
        "7D",
        "7H",
        "7S",
        "8C",
        "8D",
        "8H",
        "8S",
        "9C",
        "9D",
        "9H",
        "9S",
        "AC",
        "AD",
        "AH",
        "AS",
        "JC",
        "JD",
        "JH",
        "JS",
        "KC",
        "KD",
        "KH",
        "KS",
        "QC",
        "QD",
        "QH",
        "QS",
    ],

    DRAWING_IMG_BACK_COLOR: [
        "blue",
        "gray",
        "green",
        "purple",
        "red",
        "yellow",
    ],
};
